#模拟两个EurekaServer
#端口1800 , 1900
#两个server需要相互注册
spring:
  application:
    name: eureka-server

server:
  port: 1800
  servlet:
    context-path: /erueka-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否将自己注册到注册中心
    fetch-registry: false #是否从eureka中获取注册信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/${spring.application.name}
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 4000 #剔除服务间隔